# this image contains echo to print text message
apiVersion: v1
kind: Pod
metadata:
  name: custom-port
spec:
  containers:
    - name: nginx-content
      image: pavanidevops78/kubernetes:v4
      ports:
       - containerPort: 3000
         hostPort: 3000

---
apiVersion: v1
kind: Pod
metadata:
  name: default-port
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 3001