apiVersion: v1
kind: Pod
metadata:
  name: demo1
spec:
  containers:
    - name: nginx
      image: nginx:1.27


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    appName: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      appName: catalogue
  template:
    metadata:
      labels:
        appName: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          env:
           - name: INSTANA_DISABLE_TRACING
             value: "true"