apiVersion: v1
kind: Pod
metadata:
  name: demo1
spec:
  containers:
    - name: nginx
      image: nginx:1.27


---
apiVersion: v1
kind: Pod
metadata:
  name: instana-demo
spec:
  containers:
    - name: node
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
      env:
       - name: INSTANA_DISABLE_TRACING
         value: "true"