apiVersion: v1
kind: Pod
metadata:
  name: demo1
spec:
  containers:
    - name: nginx
      image: nginx:1.27


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    appName: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      appName: catalogue
  template:
    metadata:
      labels:
        appName: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          env:
           - name: INSTANA_ENABLED
             value: "false"
           - name: MONGO
             value: "true"
           - name: MONGO_URL
             value: "mongodb://172.31.17.236:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    appName: user
spec:
  replicas: 1
  selector:
    matchLabels:
      appName: user
  template:
    metadata:
      labels:
        appName: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          env:
            - name: MONGO
              value: "true"
            - name: INSTANA_ENABLED
              value: "false"
            - name: MONGO_URL
              value: "mongodb://172.31.17.236:27017/users"
            - name: REDIS_URL
              value: "redis://172.31.25.13:6379"





---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-schema-job
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: "mongo"
            - name: APP_GIT_URL
              value: "https://github.com/roboshop-devops-project-v3/catalogue"
            - name: INSTANA_ENABLED
              value: "false"
            - name: DB_HOST
              value: "172.31.17.236"
            - name: SCHEMA_FILE
              value: "db/master-data.js"

      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    appName: catalogue
  ports:
    - port: 8080 # Service port [internally load balancer service port is 80 ]
      targetPort: 8080  # Pod container port
  type: ClusterIP