apiVersion: v1
kind: Pod
metadata:
  name: pod-lb
  labels:
    appName: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  selector:
    appName: roboshop
  ports:
    - port: 8006 # Service port [LB service port listens on 80 only ]
      targetPort: 80  # Pod container port
  type: ExternalName
