apiVersion: v1
kind: Pod
metadata:
  name: demo3
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

    - name: nginx-content
      image: pavanidevops78/kubernetes:v4
      ports:
        - containerPort: 8000