apiVersion: v1
kind: Pod
metadata:
  name: pod-lb
  labels:
    appName: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  selector:
    appName: roboshop
  ports:
    - port: 80 # Service port [we can give service port ]
      targetPort: 80  # Pod container port
  type: LoadBalancer
