apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeport
  labels:
    appName: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-01
spec:
  selector:
    app: roboshop
  ports:
    - port: 8004 # Service port [we can give service port ]
      targetPort: 80  # Pod container port
  type: NodePort


# here increased one more node and check the client request[ i means two nodes Node A and Node B with same port,check endpoints]
